### ISSUE TITLE
Including to microauth collection

### ISSUE THREAD

**Issue by dimapaloskin** [microauth/microauth-vkontakte#6]
What you think about including to [microauth](https://github.com/microauth/)? :)

**Comment by rockchalkwushock** [comment]
@dimapaloskin 

Yeah, I think it's best to consolidate the package with the others for other developer's sake of finding. I've never done anything like this so you will have to let me know how to go about adding it to the organization.

**Comment by dimapaloskin** [comment]
At first you need to approve invitation to https://github.com/orgs/microauth
After you need to go repo settings and transfer repository to microauth.

[Instructions](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/)

Also, you need yo update origin in your local copy.
Let me know if you will have questions or problems.

Thank you! :)

**Comment by rockchalkwushock** [comment]
@dimapaloskin 

Github is in the process of transferring ownership now.

I assume you mean update the origin on the local copy on my machine? 

```sh
rockchalkwushock in microauth-vkontakte on master $ git branches
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/greenkeeper/initial
  remotes/origin/master
```

or perhaps you mean the links with in the `package.json`?

```json
{
 "homepage": "https://github.com/rockchalkwushock/microauth-vkontakte#readme",
 "repository": "https://github.com/rockchalkwushock/microauth-vkontakte.git",
 "bugs": "https://github.com/rockchalkwushock/microauth-vkontakte/issues",
}
```

**Comment by rockchalkwushock** [comment]
I see now that you meant the links within the repository itself. My only question comes with the badges that are tracking the build & coverage. Those are linked directly to my accounts with CircleCi, Codecov, etc. Since any pushes are no longer going to `rockchalkwushock/microauth-vkontakte` I imagine that no build, coverage, etc will be run/produced corresponding to the badges. I don't know if organizations have settings like user's do on Github, we could possibly create accounts with those vendors under the `microauth` name.

### Current Bug :bug:

At the moment the only way to push any changes to the repo and not receive a broken build is to _patch_ the package. I opened this issue with CircleCi support to try and come up with a solution. Right now what happens is if `semantic-release` does not see any valid changes that would cause a SemVer change & need to publish to the registry it aborts causing CircleCi to fail. 

https://discuss.circleci.com/t/circleci-semantic-release/15728

**Comment by dimapaloskin** [comment]
Unfortunately I didn't use CircleCi yet.
Let me know if I need to do something for help you.

**Comment by rockchalkwushock** [comment]
It's up to you if you want to create an account for `microauth` with these services. What are you guys using now? I'd personally like to keep `nsp` & `snyk` just so user's of the package know that there are no vulnerabilities to the dependencies. As for coverage I just find `codecov` to be easier to integrate with & I just started working with `circle ci`. It's faster than `travis ci` albeit has a rather steep learning curve & few examples with the latest `v2.0` documentation.

### Integrations already present:

- [CircleCi](https://circleci.com)
- [Codecov](https://codecov.io)
- [Node Security Platform](https://nodesecurity.io)
- [Snyk](https://snyk.io)

**Comment by dimapaloskin** [comment]
@rockchalkwushock 

What email (or username) I need to use to invite you.
At least it's needed for nsp.
Looks like github authorization enough for control microauth stuff :)

**Comment by dimapaloskin** [comment]
I also updated main repo. I did add microauth-vkontakte in the list of modules and also I added your name to Authors section. Let's rock \m/

**Comment by rockchalkwushock** [comment]
@dimapaloskin 

email: rockchalkwushock@icloud.com

**Comment by rockchalkwushock** [comment]
@dimapaloskin 

I see `microauth` as an organization for me to switch too on CircleCi & CodeCov and this package is present in both. As for `snyk` I haven't found anything on my dashboard or the settings that show the same. I did see there is a _invitation link_ perhaps if you use my email you can _invite_ me to the organization's page on `snyk`?

**Comment by dimapaloskin** [comment]
@rockchalkwushock 

Done!
